use_default_settings: true

server:
  secret_key: "ceclaw-searxng-key-2026"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json

general:
  debug: false
  instance_name: "CECLAW Search"
